DE-5407 Add pagination component for php
BrandEmbassy/ui-components pull request #273
Opened 2021-04-27 23:32 UTC by abcondas

2021-05-03 08:47 UTC, milan-zelenka commented on src-php/Navigation/Pagination/Pagination.php
> +        }
```suggestion
        if (!$styles) {
            return self::BLANK;
        }
```
I would switch the statement like that so you don't need to type cast to bool

2021-05-03 08:48 UTC, milan-zelenka approved these changes

2021-05-04 08:12 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +        return self::BLANK;
```suggestion
       return FileSystem::read(__DIR__ . '/css/Pagination.css');
```

2021-05-04 08:19 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +        return sprintf('<a %s%s>%d</a>', $class, $href, $pageNumber);
[O] We like to use early return instead of else https://github.com/BrandEmbassy/developers-manifest/issues/365 & https://github.com/BrandEmbassy/developers-manifest/issues/364 - I will mention it in the manifesto as well..

```suggestion
        if ($pageNumber === $this->pageNumberRequested) {
            return sprintf('<a class="current">%d</a>', $pageNumber);
        }
        
        return sprintf('<a href="%s/%d">%d</a>', $this->pageRoutePath, pageNumber, $pageNumber);
        

        return sprintf('<a %s%s>%d</a>', $class, $href, $pageNumber);
```

2021-05-04 08:20 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +        $svgContents = file_get_contents(__DIR__ . '/images/' . $svgName . '.svg');
```suggestion
        $svgContents = FileSystem::read(__DIR__ . '/images/' . $svgName . '.svg');
```

2021-05-04 08:20 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +        $svgContents = file_get_contents(__DIR__ . '/images/' . $svgName . '.svg');
Using this you don't need to check if file exists

2021-05-04 08:21 UTC, dominikvoda commented on src-php/Navigation/Pagination/css/Pagination.css
> +.main {
Why we don't have these components in stored in main css file?

2021-05-04 08:23 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +        return $anchors;
I would move this into special method (e.g. `renderPageAnchors(int $firstPage, int $lastPage): string`) and then you can easily use early return instead of else & else if

2021-05-04 08:24 UTC, dominikvoda requested changes
There are no tests for this component

2021-05-04 08:25 UTC, dominikvoda commented
> There are no tests for this component

My bad...didn't mention there is no `Review ready` label yet..

2021-05-12 20:44 UTC, abcondas commented on src-php/Navigation/Pagination/css/Pagination.css
> +.main {
@dominikvoda where do you want them, specifically?  I personally don't like the idea of separating the .css from it's component but I will put the file wherever you want just let me know where.

2021-05-12 21:19 UTC, abcondas commented
> > There are no tests for this component
> 
> My bad...didn't mention there is no `Review ready` label yet..

Yes, I will be doing the tests next.  I wanted to get a preliminary review done before I left on vacation.

2021-05-13 08:27 UTC, milan-zelenka approved these changes

2021-05-17 18:30 UTC, abcondas commented on src/package/components/Statuses/Statuses.js
> +  }
Fixing php error on `.toLowerCase` function since`text` is a null, string or React:Node type

2021-05-18 13:40 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +            . '<table cellpadding="0" cellspacing="0" width="100%" border="0">'
is it possible to move these style attributes to css directly?

2021-05-18 13:41 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +    }
this should not be needed

2021-05-18 13:44 UTC, dominikvoda approved these changes
Approved PHP component, but we figured out with @jindrichsamec that this approach where css is not in react modules is not working for concat/build css file... We need to move it into react modules to make it work without changing webpack and staff

2021-05-18 13:45 UTC, jindrichsamec commented on src/package/components/Base.css
> +@import "./../../../src-php/Navigation/Pagination/Pagination.css";
It's better to follow current conventions and import stylesheet via `/src/package/components/Pagination/Pagination.css` because it will create class names with the prefix `Pagination__*`. Now it will create the prefix `Base__*` because it is in the Base.css file.

I know it isn't the best solution, but it works now. We can design a better solution in the future.

2021-05-20 08:26 UTC, dominikvoda commented on src-php/Navigation/Pagination/Pagination.php
> +            '<a href="%s?pageNumber=%2$d">%2$d</a>',
I don't think this will work, in current URI you can already have query parameters with question mark so you should parse query string and add it there

2021-05-20 19:38 UTC, jindrichsamec commented on src/package/components/Statuses/Statuses.js
> +      altText = renderToString(text ?? '')
`??`expression is the root cause of the lint error because it isn't supported by the javascript/babel version in this project. You have to change it to `text !== null && text !== undefined ? text : ''`

2021-05-20 19:39 UTC, jindrichsamec commented on src/package/components/Pagination/Pagination.css
> +}
missing new line at the end of the file

2021-05-24 06:22 UTC, vojtahavranek approved these changes

2021-05-28 18:48 UTC, merged